export const INGREDIENTS_BUN = "bun"
export const INGREDIENTS_SAUCE = 'sauce';
export const INGREDIENTS_MAIN = 'main';
export const INGREDIENTS_BUN_NAME = "Булки"
export const INGREDIENTS_SAUCE_NAME = 'Соусы';
export const INGREDIENTS_MAIN_NAME = 'Начинки';
export const NORMA_URL= 'https://norma.nomoreparties.space/api';
export const GET_INGREDIENTS_URL = '/ingredients';
export const SET_INGREDIENTS_URL = '/orders';