export const INGREDIENTS_BUN = "bun"
export const INGREDIENTS_SAUCE = 'sauce';
export const INGREDIENTS_MAIN = 'main';
export const INGREDIENTS_BUN_NAME = "Булки"
export const INGREDIENTS_SAUCE_NAME = 'Соусы';
export const INGREDIENTS_MAIN_NAME = 'Начинки';
export const NORMA_URL= 'https://norma.nomoreparties.space/api';
export const GET_INGREDIENTS_URL = '/ingredients';
export const SET_INGREDIENTS_URL = '/orders';
export const FORGOT_PASSWORD_URL = '/password-reset';
export const REGISTER_URL = '/auth/register';
export const LOGIN_URL = '/auth/login';
export const LOGOUT_URL = '/auth/logout';
export const RASSWORD_RESET_URL = '/password-reset/reset';
export const TOKEN_URL = '/auth/token';
export const AUTH_USER_URL = '/auth/user';
